  
name: Builds for various architectures

on:
  push:
    branches:
    - feature/*
    - ci
  pull_request:
    branches:
      - ci

jobs:
 build:

    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
      working-directory: ./builder
    strategy:
      matrix:
        destination: ["OS=14.0,name=iPhone 11 Pro"]
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project tealium-swift.xcodeproj -scheme "TealiumCore" -destination "${{ matrix.destionation}}" clean build | xcpretty
        working-directory: ${{env.working-directory}}

          