  
name: Tests and code coverage

on:
  push:
    branches:
    - feature/*
    - ci

jobs:
  test_iOS:
    name: iOS Test
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
      working-directory: ./builder
    strategy:
      matrix:
        scheme: 
          - TealiumCoreTests-iOS
          - TealiumCollectTests-iOS
          - TealiumLifecycleTests-iOS
          - TealiumVisitorServiceTests-iOS
          - TealiumTagManagementTests-iOS
          - TealiumRemoteCommandsTests-iOS
          - TealiumAttributionTests-iOS
          - TealiumAutoTrackingTests-iOS
        # todo: location tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: Test - ${{ matrix.scheme }}
        run: fastlane scan --scheme "${{ matrix.scheme }}" --output_files "${{ matrix.scheme }}".html
        working-directory: ${{env.working-directory}}
      - name: archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{env.working-directory}}/test_output/*.html
  test_macOS:
    name: macOS Build and Test
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
      working-directory: ./builder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: Test TealiumCoreTests-macOS
        run: fastlane scan --scheme TealiumCoreTests-macOS --output_files CoreTests-macOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumCollectTests-macOS
        run: fastlane scan --scheme TealiumCollectTests-macOS --output_files CollectTests-macOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumLifecycleTests-macOS
        run: fastlane scan --scheme TealiumLifecycleTests-macOS --output_files LifecycleTests-macOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumVisitorServiceTests-macOS
        run: fastlane scan --scheme TealiumVisitorServiceTests-macOS --output_files VisitorServiceTests-macOS.html
        working-directory: ${{env.working-directory}}
      - name: archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{env.working-directory}}/test_output/*.html
  test_tvOS:
    name: tvOS Build and Test
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
      working-directory: ./builder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: Test TealiumCoreTests-macOS
        run: fastlane scan --scheme TealiumCoreTests-tvOS --output_files CoreTests-tvOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumCollectTests-tvOS
        run: fastlane scan --scheme TealiumCollectTests-tvOS --output_files CollectTests-tvOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumLifecycleTests-tvOS
        run: fastlane scan --scheme TealiumLifecycleTests-tvOS --output_files LifecycleTests-tvOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumVisitorServiceTests-tvOS
        run: fastlane scan --scheme TealiumVisitorServiceTests-tvOS --output_files VisitorServiceTests-tvOS.html
        working-directory: ${{env.working-directory}}
      - name: archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{env.working-directory}}/test_output/*.html
