  
name: Tests and code coverage

on:
  push:
    branches:
    - feature/*
    - ci

jobs:
  test_iOS:
    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
      working-directory: ./builder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: Test TealiumCoreTests-iOS
        run: fastlane scan --scheme TealiumCoreTests-iOS --output_files CollectTests-iOS.html
        working-directory: ${{env.working-directory}}
      - name: Test TealiumCollectTests-iOS
        run: fastlane scan --scheme TealiumCoreTests-iOS --output_files CoreTests-iOS.html
        working-directory: ${{env.working-directory}}
      - name: archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{env.working-directory}}/test_output/*.html
  test_macOS:
    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
      working-directory: ./builder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: Test TealiumCoreTests-macOS --output_files CoreTests-macOS.html
        run: fastlane scan --scheme TealiumCoreTests-macOS
        working-directory: ${{env.working-directory}}
      - name: archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{env.working-directory}}/test_output/*.html
          